#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:

          cat >> .config <<EOF
          CONFIG_TARGET_IMAGES_GZIP=y
          CONFIG_KERNEL_BUILD_USER="OpenWrt-CI"
          CONFIG_KERNEL_BUILD_DOMAIN="Azure"
	  CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_PACKAGE_grub2-efi=y
	  CONFIG_EFI_IMAGES=y
	  CONFIG_TARGET_IMAGES_GZIP=y
	  CONFIG_TARGET_KERNEL_PARTSIZE=16
	  CONFIG_TARGET_ROOTFS_PARTSIZE=300
	  # CONFIG_GRUB_CONSOLE is not set
	  # CONFIG_PACKAGE_luci-app-docker=y
	  # CONFIG_PACKAGE_luci-i18n-docker-zh-cn=y
	  # CONFIG_PACKAGE_luci-app-qbittorrent is not set
	  #CONFIG_PACKAGE_luci-app-ssr-plus=y
	  #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
	  #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks_Rust=y
	  #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_plugin=y
	  #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Xray=y
 	  #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
	  #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Redsocks2=y
	  #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_NaiveProxy=y
	  #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
	  #CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
	  #CONFIG_PACKAGE_luci-i18n-ssr-plus-zh-cn=y
	  CONFIG_PACKAGE_luci-app-advanced=y	  
	  CONFIG_PACKAGE_luci-theme-argon=y
	  CONFIG_PACKAGE_luci-theme-atmaterial_new=y
	  CONFIG_PACKAGE_luci-theme-mcat=y
	  CONFIG_PACKAGE_luci-theme-tomato=y
	  CONFIG_PACKAGE_luci-theme-ifit=y
	  CONFIG_PACKAGE_luci-theme-mcat=y
	  CONFIG_PACKAGE_luci-theme-tomato=y
	  CONFIG_PACKAGE_luci-app-mwan3=y
	  CONFIG_PACKAGE_luci-app-mwan3helper=y
	  CONFIG_PACKAGE_luci-i18n-mwan3-zh-cn=y
	  CONFIG_PACKAGE_luci-i18n-mwan3helper-zh-cn=y
	  CONFIG_PACKAGE_luci-app-syncdial=y
	  CONFIG_PACKAGE_luci-app-ttyd=y
	  CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
	  CONFIG_PACKAGE_luci-app-webadmin=y
	  CONFIG_PACKAGE_luci-i18n-webadmin-zh-cn=y
	  CONFIG_PACKAGE_dnsmasq_full_auth=y
	  CONFIG_PACKAGE_dnsmasq_full_conntrack=y
	  CONFIG_PACKAGE_dnsmasq_full_dnssec=y
	  CONFIG_PACKAGE_ddns-scripts_cloudflare.com-v4=y
	  CONFIG_PACKAGE_ddns-scripts_freedns_42_pl=y
	  CONFIG_PACKAGE_ddns-scripts_godaddy.com-v1=y
	  CONFIG_PACKAGE_ddns-scripts_no-ip_com=y
	  CONFIG_PACKAGE_ddns-scripts_nsupdate=y
	  CONFIG_PACKAGE_ddns-scripts_route53-v1=y
	  CONFIG_PACKAGE_curl=y
	  CONFIG_PACKAGE_htop=y
	  CONFIG_PACKAGE_nano=y
	  CONFIG_PACKAGE_wget=y
	  CONFIG_PACKAGE_kmod-kvm-amd=y
	  CONFIG_PACKAGE_kmod-kvm-intel=y
	  CONFIG_PACKAGE_kmod-kvm-x86=y
	  CONFIG_OPENSSL_ENGINE_CRYPTO=y
	  CONFIG_OPENSSL_ENGINE_DIGEST=y
	  CONFIG_OPENSSL_WITH_CAMELLIA=y
	  CONFIG_OPENSSL_WITH_COMPRESSION=y
	  CONFIG_OPENSSL_WITH_DTLS=y
	  CONFIG_OPENSSL_WITH_EC2M=y
	  CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
	  CONFIG_OPENSSL_WITH_GOST=y
	  CONFIG_OPENSSL_WITH_IDEA=y
	  CONFIG_OPENSSL_WITH_MDC2=y
	  CONFIG_OPENSSL_WITH_RFC3779=y
	  CONFIG_OPENSSL_WITH_SEED=y
	  CONFIG_OPENSSL_WITH_WHIRLPOOL=y
	  CONFIG_OPENVPN_openssl_ENABLE_DEF_AUTH=y
	  CONFIG_OPENVPN_openssl_ENABLE_FRAGMENT=y
	  CONFIG_OPENVPN_openssl_ENABLE_LZ4=y
	  CONFIG_OPENVPN_openssl_ENABLE_LZO=y
	  CONFIG_OPENVPN_openssl_ENABLE_MULTIHOME=y
	  CONFIG_OPENVPN_openssl_ENABLE_PF=y
	  CONFIG_OPENVPN_openssl_ENABLE_PORT_SHARE=y
	  CONFIG_OPENVPN_openssl_ENABLE_SERVER=y
	  CONFIG_OPENVPN_openssl_ENABLE_SMALL=y
	  CONFIG_KERNEL_BUILD_USER="eSir Playground"
	  CONFIG_GRUB_TITLE="OpenWrt AutoBuild by eSirPlayground"
	  CONFIG_PACKAGE_kmod-usb-ohci=y
	  CONFIG_PACKAGE_kmod-usb-ohci-pci=y
	  CONFIG_PACKAGE_kmod-usb-storage-uas=y
	  CONFIG_PACKAGE_kmod-usb-uhci=y
	  CONFIG_PACKAGE_kmod-sdhci=y
	  CONFIG_PACKAGE_kmod-usb-ehci=y
	  CONFIG_PACKAGE_kmod-usb2=y
	  CONFIG_PACKAGE_kmod-usb2-pci=y
	  CONFIG_PACKAGE_kmod-usb3=y
	  CONFIG_PACKAGE_luci-app-frpc=y
	  CONFIG_PACKAGE_luci-app-aliddns=y
	  CONFIG_PACKAGE_luci-app-smartdns=y
	  CONFIG_PACKAGE_luci-app-store=y
	  CONFIG_PACKAGE_luci-app-lucky=y
	  CONFIG_PACKAGE_luci-app-openclash=y
	  #CONFIG_PACKAGE_luci-app-passwall=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Brook=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ChinaDNS_NG=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Haproxy=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Hysteria=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Kcptun=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_NaiveProxy=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_PDNSD=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Server=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_GO=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray=y
	  #CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray_Plugin=y
          EOF

          #
          # ===============================================================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
